version: '3.7'

services:
  todolist:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./todolist:/todolist
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
   
