# Generated by Django 3.2.4 on 2021-11-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
